export default interface IColorsPallete {
    backgroundColor: string,
    onBackgroundColor: string,
    onBackgroundLowColor: string,
    onBackgroundMediumColor: string,
    onBackgroundHighColor: string,
    surfaceColor: string,
    onSurfaceColor: string,
    primaryColor: string,
    onPrimaryColor: string,
    secondaryColor: string,
    onSecondaryColor: string,
    successColor: string,
    onSuccessColor: string,
    errorColor: string,
    onErrorColor: string,
    warningColor: string,
    onWarningColor: string,
}